export const constant = {
    tokenKey: 'javpcHqshWPsgGQQKqdN',
    usernameKey: 'PEhwqEQWnjEdbRGwXTss',
    userInfoKey: 'hyfEFaNxatgGjHDWDiAT',
    localeKey: 'kxJdCX1tHJQJM1yYFH6P',
    tabBarPagePathKey: 'EnCQAWwPsAZZGMrAmsLE',
    appConfigKey: 'lboyzgty3cfdqftgketd',
    chargeTuneKey: 'pw0gamano6fnmnefvher',
    klineChartStatus: 'qdcm1cti8znqnh5g8cue',
    hasJumpToAddWallet: 'hn5cnyz11j3yol6svjer',
    signMessage: 'mdpdsrgy7apqhaky6dwt',
    curWalletAddress:'KDLTYBi7f43HhGrrpM4U',
    lastWalletRdnsKey:'UNQfPc8LKJ0g3Az4z4RH',
    refreshTokenKey:'1870CdXLdqc2ei8B6cfJ',
    predictionRecordKey: 'hrfBKNnuU5BWJcckrQ81',
    pointsInfoKey: 'h57zg4P3FJX27LM9YUvM',
    updateTokenTime: 'sM9RRXCHGSnYXH34EnXM',
}