---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: yesornoa-web
  name: yesornoa-web
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/name: yesornoa-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/name: yesornoa-web
    spec:
      containers:
        - image: 'ghcr.io/yes-or-no-labs/yesorno-web:{{IMAGE_VERSION}}'
          imagePullPolicy: IfNotPresent
          name: yesorno-web
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: github-docker-repo
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: yesornoa-web
  name: yesornoa-web
  namespace: default
spec:
  clusterIP: 10.43.92.50
  clusterIPs:
    - 10.43.92.50
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.kuboard.cn/name: yesornoa-web
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: yesornoa-web
  name: yesornoa-web
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: dev.yesornolabs.xyz
      http:
        paths:
          - backend:
              service:
                name: yesornoa-web
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - dev.yesornolabs.xyz
      secretName: yesornolabs.xyz

