name: Build And Deploy

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get-commit-sha.outputs.sha }}
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        id: get-commit-sha
        run: echo "::set-output name=sha::$(git rev-parse --short=7 HEAD)"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: "ghcr.io"

      - name: Build and push Docker image
        env:
          COMMIT_SHA: ${{ steps.get-commit-sha.outputs.sha }}

        run: |
          IMAGE_URL="ghcr.io/yes-or-no-labs/yesorno-web-pord:${COMMIT_SHA}"
          echo $IMAGE_URL
          docker build -t ${IMAGE_URL} -f docker/online.dockerfile .
          docker push ${IMAGE_URL}
      - name: Update Deploy Version
        run: |
          sed -i 's|{{IMAGE_VERSION}}|${{ steps.get-commit-sha.outputs.sha }}|g' apply/prod-apply.yaml

      - name: Deploy to k3s
        uses: steebchen/kubectl@master
        with:
          config: ${{ secrets.DOCKER_KUBE }}
          command: apply -f apply/prod-apply.yaml
